'use client';
import { useState, useEffect } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { motion } from 'framer-motion';
import { 
  Brain, 
  CheckCircle2, 
  Target, 
  MessageSquare, 
  Zap, 
  Shield, 
  ArrowLeft, 
  Copy, 
  Activity
} from 'lucide-react';
interface RecapData {
  title: string;
  tldr: string;
  keyPoints: string[];
  actionItems: Array<{task: string, owner: string}>;
  decisions: string[];
  sentiment: string;
  engagementScore: number;
}

export default function RecapPage() {
  const { roomId } = useParams();
  const router = useRouter();
  const [recap, setRecap] = useState<RecapData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchRecap = async () => {
      try {
        const res = await fetch(`/api/recap?roomId=${roomId}`);
        const data = await res.json();
        if (data.error) throw new Error(data.error);
        setRecap(data);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchRecap();
  }, [roomId]);

  const copyRecap = () => {
    if (!recap) return;
    const text = `
Neural Recap: ${recap.title}
TL;DR: ${recap.tldr}

Key Points:
${recap.keyPoints.map((p: string) => `- ${p}`).join('\n')}

Action Items:
${recap.actionItems.map((a: {task: string, owner: string}) => `- ${a.task} (Owner: @${a.owner})`).join('\n')}

Decisions:
${recap.decisions.map((d: string) => `- ${d}`).join('\n')}

Generated by Confera AI
    `.trim();
    navigator.clipboard.writeText(text);
    alert('Recap copied to secure clipboard!');
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-[#09090b] flex flex-col items-center justify-center space-y-6">
        <div className="relative">
          <Brain className="animate-pulse text-indigo-500 w-16 h-16" />
          <div className="absolute inset-0 bg-indigo-500/20 blur-xl animate-ping rounded-full" />
        </div>
        <div className="flex flex-col items-center gap-2">
          <p className="text-[10px] font-black text-slate-500 uppercase tracking-[0.3em]">Downloading Neural Data...</p>
          <div className="w-48 h-1 bg-slate-800 rounded-full overflow-hidden">
            <motion.div 
              animate={{ x: ['-100%', '100%'] }}
              transition={{ repeat: Infinity, duration: 1.5, ease: 'linear' }}
              className="w-1/2 h-full bg-indigo-500"
            />
          </div>
        </div>
      </div>
    );
  }

  if (!recap) {
    return (
      <div className="min-h-screen bg-[#09090b] flex flex-col items-center justify-center p-8 text-center">
        <Shield className="text-rose-500 w-16 h-16 mb-4 opacity-20" />
        <h2 className="text-xl font-bold text-white mb-2 tracking-tight">Neural Link Severed</h2>
        <p className="text-slate-500 text-sm mb-8 max-w-xs">The session data for this node could not be recovered from the mesh.</p>
        <button 
          onClick={() => router.push('/dashboard')} 
          className="px-8 py-3 bg-[#111113] border border-[#27272a] rounded-xl text-[10px] font-black uppercase tracking-widest text-slate-300 hover:text-white hover:border-slate-700 transition-all"
        >
          Return to Dashboard
        </button>
      </div>
    );
  }

  const container = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: { staggerChildren: 0.1, delayChildren: 0.2 }
    }
  };

  const item = {
    hidden: { y: 20, opacity: 0 },
    show: { y: 0, opacity: 1, transition: { type: 'spring', damping: 20 } }
  };

  return (
    <div className="min-h-screen bg-[#09090b] text-slate-200 font-inter selection:bg-indigo-500/30 pb-32">
      {/* Header */}
      <header className="h-20 border-b border-[#27272a]/50 bg-[#09090b]/80 backdrop-blur-2xl sticky top-0 z-50">
        <div className="max-w-5xl mx-auto px-6 h-full flex items-center justify-between">
           <button onClick={() => router.push('/dashboard')} className="flex items-center gap-2 text-slate-500 hover:text-white transition-colors group">
              <ArrowLeft size={16} className="group-hover:-translate-x-1 transition-transform" />
              <span className="text-[10px] font-black uppercase tracking-widest">Dashboard</span>
           </button>
           <div className="flex items-center gap-2">
             <Brain size={20} className="text-indigo-500" />
             <h1 className="text-xs font-black uppercase tracking-[0.2em] text-white">Intelligence Recap</h1>
           </div>
           <button 
             onClick={copyRecap} 
             className="flex items-center gap-2 px-4 py-2 bg-indigo-600 rounded-xl text-white shadow-lg shadow-indigo-500/20 hover:bg-indigo-500 transition-all text-[10px] font-black uppercase tracking-widest"
           >
             <Copy size={14} />
             <span className="hidden sm:inline">Export</span>
           </button>
        </div>
      </header>

      <motion.main 
        variants={container}
        initial="hidden"
        animate="show"
        className="max-w-5xl mx-auto px-6 pt-12 space-y-8"
      >
         {/* Hero Recap Card */}
         <motion.div variants={item} className="p-8 md:p-12 bg-[#111113] border border-[#27272a] rounded-[40px] relative overflow-hidden shadow-2xl group">
            <div className="absolute top-0 right-0 p-12 opacity-[0.03] group-hover:opacity-10 transition-opacity">
              <Brain size={180} className="text-indigo-500" />
            </div>
            <div className="relative z-10">
               <div className="flex items-center gap-2 mb-4">
                  <span className="text-[10px] font-black text-indigo-500 uppercase tracking-[0.4em]">Neural Analysis Output</span>
                  <div className="h-[1px] w-12 bg-indigo-500/30" />
               </div>
               <h2 className="text-4xl md:text-5xl font-black text-white tracking-tighter mb-6 leading-tight">{recap.title}</h2>
               <p className="text-xl text-slate-400 font-medium leading-relaxed max-w-3xl italic border-l-2 border-indigo-500/30 pl-6">
                 &quot;{recap.tldr}&quot;
               </p>
            </div>
            
            <div className="mt-12 pt-8 border-t border-[#27272a] flex flex-wrap items-center gap-8">
               <div className="flex flex-col gap-1">
                  <span className="text-[9px] font-black text-slate-600 uppercase tracking-widest">Sentiment State</span>
                  <div className={`px-3 py-1 rounded-lg text-[10px] font-black uppercase tracking-widest w-fit ${recap.sentiment === 'positive' ? 'bg-emerald-500/10 text-emerald-500 border border-emerald-500/20' : recap.sentiment === 'tense' ? 'bg-rose-500/10 text-rose-500 border border-rose-500/20' : 'bg-slate-500/10 text-slate-500 border border-slate-500/20'}`}>
                    {recap.sentiment}
                  </div>
               </div>
               <div className="flex-1 min-w-[240px]">
                  <div className="flex justify-between items-center mb-2.5 px-1">
                    <span className="text-[9px] font-black text-slate-600 uppercase tracking-widest">Cognitive Engagement</span>
                    <span className="text-xs font-black text-indigo-500 tabular-nums">{recap.engagementScore}%</span>
                  </div>
                  <div className="h-2 w-full bg-[#09090b] border border-[#27272a] rounded-full overflow-hidden p-0.5">
                    <motion.div 
                      initial={{ width: 0 }}
                      animate={{ width: `${recap.engagementScore}%` }}
                      transition={{ duration: 1.5, ease: "easeOut", delay: 0.8 }}
                      className="h-full bg-gradient-to-r from-indigo-600 to-blue-500 rounded-full shadow-[0_0_10px_rgba(99,102,241,0.3)]"
                    />
                  </div>
               </div>
            </div>
         </motion.div>

         <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {/* Key Points */}
            <motion.div variants={item} className="p-8 bg-[#111113] border border-[#27272a] rounded-[32px] shadow-xl hover:border-slate-700 transition-colors">
               <div className="flex items-center gap-3 mb-8">
                 <div className="p-2 bg-amber-500/10 rounded-xl text-amber-500">
                    <Zap size={18} />
                 </div>
                 <h3 className="text-[10px] font-black uppercase tracking-widest text-white">Neural Insights</h3>
               </div>
               <ul className="space-y-5">
                  {recap.keyPoints.map((point: string, i: number) => (
                    <li key={i} className="flex gap-4 items-start group">
                       <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-indigo-500/40 group-hover:bg-indigo-500 group-hover:scale-125 transition-all shrink-0" />
                       <p className="text-sm text-slate-400 font-medium leading-snug group-hover:text-slate-200 transition-colors">{point}</p>
                    </li>
                  ))}
               </ul>
            </motion.div>

            {/* Decisions */}
            <motion.div variants={item} className="p-8 bg-[#111113] border border-[#27272a] rounded-[32px] shadow-xl hover:border-slate-700 transition-colors">
               <div className="flex items-center gap-3 mb-8">
                 <div className="p-2 bg-indigo-500/10 rounded-xl text-indigo-500">
                    <Target size={18} />
                 </div>
                 <h3 className="text-[10px] font-black uppercase tracking-widest text-white">Core Decisions</h3>
               </div>
               <div className="space-y-4">
                  {recap.decisions.map((decision: string, i: number) => (
                    <div key={i} className="flex gap-4 p-4 bg-[#09090b] border border-[#27272a] rounded-2xl group hover:border-indigo-500/30 transition-all">
                       <CheckCircle2 size={18} className="text-emerald-500 shrink-0 mt-0.5" />
                       <p className="text-sm font-bold text-white leading-tight tracking-tight">{decision}</p>
                    </div>
                  ))}
               </div>
            </motion.div>
         </div>

         {/* Action Items */}
         <motion.div variants={item} className="p-8 bg-[#111113] border border-[#27272a] rounded-[32px] shadow-xl overflow-hidden">
            <div className="flex items-center gap-3 mb-8 px-2">
               <div className="p-2 bg-blue-500/10 rounded-xl text-blue-500">
                  <MessageSquare size={18} />
               </div>
               <h3 className="text-[10px] font-black uppercase tracking-widest text-white">Action Matrix</h3>
            </div>
            <div className="overflow-x-auto custom-scrollbar">
               <table className="w-full text-left min-w-[500px]">
                  <thead>
                     <tr className="border-b border-[#27272a]">
                        <th className="pb-4 text-[9px] font-black text-slate-600 uppercase tracking-widest px-4">Objective</th>
                        <th className="pb-4 text-[9px] font-black text-slate-600 uppercase tracking-widest px-4">Assigned Node</th>
                        <th className="pb-4 text-[9px] font-black text-slate-600 uppercase tracking-widest text-right px-4">Protocol Status</th>
                     </tr>
                  </thead>
                  <tbody className="divide-y divide-[#27272a]/50">
                     {recap.actionItems.map((item: {task: string, owner: string}, i: number) => (
                       <tr key={i} className="group hover:bg-[#09090b]/50 transition-colors">
                          <td className="py-5 px-4 text-sm font-bold text-slate-300 leading-tight">{item.task}</td>
                          <td className="py-5 px-4">
                             <div className="flex items-center gap-3">
                                <div className="w-7 h-7 rounded-lg bg-indigo-600/10 border border-indigo-500/20 flex items-center justify-center text-[10px] font-black text-indigo-500">
                                  {item.owner.charAt(0).toUpperCase()}
                                </div>
                                <span className="text-xs font-bold text-white group-hover:text-indigo-400 transition-colors">@{item.owner}</span>
                             </div>
                          </td>
                          <td className="py-5 px-4 text-right">
                             <span className="text-[9px] font-black uppercase tracking-[0.2em] text-indigo-400/80 bg-indigo-400/5 border border-indigo-400/10 px-3 py-1.5 rounded-lg">Pending Deployment</span>
                          </td>
                       </tr>
                     ))}
                  </tbody>
               </table>
            </div>
         </motion.div>
      </motion.main>
    </div>
  );
}
